spring:
  sql:
    init:
      mode: always

  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ec8cece030b29c31d45d0a3d8ad73f53
            client-secret: jNIaJ9uqypKpwhnxNxP0UsxmM0HO2zyi
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
            - profile_nickname

          naver:
            client-id: aHerlwHR4S77s3J3tfkk
            client-secret: 7cB8eNh2Wq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

portOne:
  api:
    secret: qOniqY41ymCeMkxxwYzKmBtWDSjDiJPQSkSRMphD8ZJVwO8bgU9UxuybhCeRYMoBdOGcaJHCChlDQ6dM


server:
  servlet:
    context-path: /